/******************************************************************************/
/***          Generated by IBExpert 2017.7.2.1 14/08/2017 15:37:09          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;

CREATE DATABASE 'd:\DevProjects\data\Teplosnab.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1251 COLLATION PXW_CYRL;

